### ISSUE TITLE
Factura con IVA error

### ISSUE THREAD

**Issue by alejandrosofter** [a2systems/odoo-argentina#3]
Hola estoy usando odoo 17 e instale esta version en 17.. tengo algunos inconvenientes con IVA .. al hacer con monotributo sin iva anda joya.. pero cuando quiero hacer una FACT A con iva ahi muestra el error:AFIP Validation Error. 10048: El campo  'Importe Total' ImpTotal, debe ser igual  a la  suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.
10020: El  campo  BaseImp  en AlicIVA es obligatorio  y debe ser mayor a 0 cero.  Hice todos los pasos de este tutorial https://a2systems.co/blog/blog-2/instalacion-de-factura-electronica-en-odoo-17-community-edition-223

**Comment by 3lk0k0** [comment]
antes que nada como hiciste para que te funcione la viculacion con afip ? yo tengo odoo 17 en debian 12 con entorno python privado para odoo , pero no puedo hacer que me conecte con afipws ! cuando creo el certificado ya no me genenera ni el request.csr

**Comment by 3lk0k0** [comment]
pudiste resolverlo ? estoy en tu misma situacion no puedo hacer ninguna factura.

**Comment by mariogustavoorrillo** [comment]
Ya esta resuelto en el branch 18.0. Funciona el Odoo 18 CE
