### ISSUE TITLE
Error AFIP 10048 y 10020 al intentar generar factura B con precio con IVA incluido

### ISSUE THREAD

**Issue by jcelguerablas** [a2systems/odoo-argentina#4]
![error IVA](https://github.com/user-attachments/assets/bde0a488-f46e-4958-b793-ed9c429c128e)

**Comment by 3lk0k0** [comment]
Hola tengo el mismo problema, y con Facturas A tambien me da el mismo error, podrias decirme si lo solucionas ?

**Comment by mariogustavoorrillo** [comment]
Ya esta resuelto en el branch 18.0. Funciona el Odoo 18 CE
